# Generated by Django 6.1 on 2026-08-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ژانر (مثل اکشن)')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام استودیو (مثل MAPPA)')),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='عنوان انگلیسی')),
                ('title_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان فارسی')),
                ('synopsis', models.TextField(verbose_name='خلاصه داستان')),
                ('episodes', models.IntegerField(default=0, verbose_name='تعداد قسمت\u200cها')),
                ('status', models.CharField(choices=[('airing', 'در حال پخش'), ('finished', 'پایان یافته'), ('upcoming', 'به زودی')], default='finished', max_length=20, verbose_name='وضعیت پخش')),
                ('genres', models.ManyToManyField(to='anime.genre', verbose_name='ژانرها')),
                ('studios', models.ManyToManyField(to='anime.studio', verbose_name='استودیوها')),
            ],
        ),
    ]
