# Generated by Django 6.1 on 2026-08-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='anime_covers/', verbose_name='عکس کاور انیمه'),
        ),
    ]
