# Generated by Django 6.1 on 2026-08-24 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_anime_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnimeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('watching', 'در حال تماشا'), ('completed', 'کامل شده'), ('on_hold', 'متوقف شده (On Hold)'), ('dropped', 'رها شده (Dropped)'), ('plan_to_watch', 'قصد تماشا دارم')], default='plan_to_watch', max_length=20, verbose_name='وضعیت')),
                ('score', models.IntegerField(default=0, verbose_name='امتیاز (۱ تا ۱۰)')),
                ('episodes_watched', models.IntegerField(default=0, verbose_name='تعداد قسمت\u200cهای دیده شده')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime', verbose_name='انیمه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لیست انیمه کاربر',
                'verbose_name_plural': 'لیست انیمه کاربران',
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
